name: Lint

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python 3.8.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.8.7
          architecture: x64

      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip setuptools wheel
            pip install -r requirements.txt

      - name: Test with pytest
        run: pytest tests

      - name: Run flake8
        run: flake8 web_shop

      - name: Run black
        run: black --check web_shop

      - name: If needed, commit black changes to the pull request
        if: failure()
        run: |
         black .
         git config --global user.name 'autoblack'
         git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
         git checkout $GITHUB_HEAD_REF
         git commit -am "fixup: Format Python code with Black"
         git push
